(* From stdpp Require Import base finite nmap. *)
(* From stdpp.bitvector Require Import definitions. *)
(* From RecordUpdate Require Import RecordSet. *)
(* From granite.core Require Import *)
(*   Bits  *)
(*   Object *)
(*   Program  *)
(*   ProgramOps. *)

(* From granite.app Require Import  *)
(*   BhtSimulates *)
(*   BtbSimulates *)
(*   Fifo1Simulates *)
(*   MemoryAPI *)
(*   MMIO *)
(*   Pipelined *)
(*   PipelinedCommon *)
(*   PipelinedAPI *)
(*   PipelinedTop *)
(*   RfScored *)
(*   ToyISA. *)
(* Set Primitive Projections. *)
(* Import RecordSetNotations. *)
(* Module TestPipeline. *)
(*   Import ISA. *)
(*   Definition mk_imem {T} (prog: list T) : Nmap T := *)
(*     list_to_map (imap (fun i a => (N.of_nat i, a)) prog). *)

(*   (* Dummy params *) *)
(*   Instance mulParams : Multiplier.MultiplierParams := *)
(*     { logNSteps := 1 }. *)
(*   Instance implParams : CPU.ImplParams := *)
(*     {| CPU.fifo1Spec := fun T _ => @Fifo1Simulates.specParams T inhabitant; *)
(*        CPU.bhtSpec := BhtSimulates.BhtSpecParams;   *)
(*        CPU.btbSpec := BtbSimulates.BtbSpecParams;   *)
(*        CPU.mulSpec := MultiplierSimulates.multiplierParams; *)
(*        CPU.decode := decode; *)
(*        CPU.execALU := execALU; *)
(*        CPU.memAddr := memAddr; *)
(*        CPU.execControl := execControl; *)
(*        CPU.isMMIO := fun _ => false *)
(*     |}.                 *)
(*   Instance memSpecParams: MemorySpec.SpecParams := *)
(*     {| MemorySpec.default_peek := fun _ => inhabitant; *)
(*        MemorySpec.resp_ready := fun _ => true; *)
(*        MemorySpec.is_full := fun _ => false *)
(*     |}. *)

(*   Instance mmioParams : MMIO.SpecParams := *)
(*     {| MMIO.peek := fun _ => {| mem_resp_addr := bv_0 _; *)
(*                              mem_resp_data := bv_0 _ |}; *)
(*        MMIO.resp_ready := fun _ => true; *)
(*        MMIO.full := fun _ => false *)
(*     |}. *)

(*   Instance imemParams: MemorySpec.SpecParams := memSpecParams. *)
(*   Instance dmemParams: MemorySpec.SpecParams := memSpecParams. *)

(*   Module ArithTest. *)

(*     Definition imem_prog := ISA.Encoding.compile_prog ArithTest.prog__double. *)
(*     Definition dmem_init : MemorySpec.memory_t := ∅. *)

(*     Definition top_spec :=  *)
(*       let initPc := zeroes in  *)
(*       let imem := mk_imem imem_prog in  *)
(*       let dmem := dmem_init in  *)
(*       @PipelinedTop.top_spec implParams imemParams dmemParams mmioParams *)
(*                                           initPc imem dmem. *)
(*     Definition test_double n := *)
(*       evalProg top_spec (PipelinedTop.step_n n) (initialState top_spec). *)

(*     Open Scope isa_scope. *)
(*     Import ISA. *)
(*     Notation prog := (prog CPU.BaseVMethod CPU.BaseMethod). *)

(*     Definition test_double_ok := (eq_refl : _ = true) : *)
(*       let '(_, st) := test_double 38 in *)
(*       let prog : prog _ := *)
(*         {{  v_x1 ← CPU.rf (RfScored.Read x.1); *)
(*             v_x2 ← CPU.rf (RfScored.Read x.2); *)
(*             v_x3 ← CPU.rf (RfScored.Read x.3); *)
(*             Return (v_x1, v_x2, v_x3) }} in *)
(*       let '((v_x1, v_x2, v_x3), _) := evalProg (CPU.base zeroes)  *)
(*                                           prog st.(PipelinedTop.Cpu ) in *)
(*       (bool_decide (v_x1 = 5%bv ) *)
(*        && (bool_decide (v_x2 = 10%bv)) *)
(*        && (bool_decide (v_x3 = 25%bv)) *)
(*       ) = true. *)
(*     (* Eval vm_compute in (test_double 38). *) *)

(*     Definition test_double_fail := (@eq_refl _ false) : *)
(*       let '(_, st) := test_double 38 in *)
(*       let prog : prog  _ := *)
(*         {{ v_x1 ← CPU.rf (RfScored.Read x.1); *)
(*            return v_x1 }} in *)
(*       let '((v_x1, _)) := evalProg (CPU.base zeroes)  *)
(*                                           prog st.(PipelinedTop.Cpu ) in *)
(*       (bool_decide (v_x1 = 4%bv)) = false. *)

(*   End ArithTest. *)

(*   Module FibTest. *)
(*     Definition imem_prog := ISA.Encoding.compile_prog MemTest.prog__fib. *)
(*     Definition dmem_init : MemorySpec.memory_t := ∅. *)

(*     Definition top_spec :=  *)
(*       let initPc := zeroes in  *)
(*       let imem := mk_imem imem_prog in  *)
(*       let dmem := dmem_init in  *)
(*       @PipelinedTop.top_spec implParams imemParams dmemParams mmioParams *)
(*                                           initPc imem dmem. *)
(*     Definition test_fib n := *)
(*       evalProg top_spec (PipelinedTop.step_n n) (initialState top_spec). *)

(*     Open Scope isa_scope. *)
(*     Import ISA. *)
(*     Notation prog := (prog CPU.BaseVMethod CPU.BaseMethod). *)

(*     Definition test_fib_ok := (@eq_refl _ true) : *)
(*       let '(_, st) := test_fib 60 in *)
(*       let dmem := st.(PipelinedTop.Dmem ).(MemorySpec.base).(MemorySpec.mem) in *)
(*       let v0 := dmem !! 0%N in *)
(*       let v1 := dmem !! 1%N in *)
(*       let v2 := dmem !! 2%N in *)
(*       let v3 := dmem !! 3%N in *)
(*       let v4 := dmem !! 4%N in *)
(*       let v5 := dmem !! 5%N in *)
(*       let v6 := dmem !! 6%N in *)
(*       bool_decide (v0 = Some 0%bv /\ *)
(*                    v1 = Some 1%bv /\ *)
(*                    v2 = Some 1%bv /\ *)
(*                    v3 = Some 2%bv /\ *)
(*                    v4 = Some 3%bv /\ *)
(*                    v5 = Some 5%bv /\ *)
(*                    v6 = Some 8%bv) = true. *)
(*   End FibTest. *)
(* End TestPipeline. *)

