(* From stdpp Require Import base finite nmap. *)
(* From stdpp.bitvector Require Import definitions. *)
(* From RecordUpdate Require Import RecordSet. *)

(* From granite.core Require Import *)
(*   Bits *)
(*   Object *)
(*   Program *)
(*   ProgramOps *)
(*   ProgramTactics *)
(*   Reg *)
(*   Tactics. *)
(* From granite.app Require Import *)
(*   BhtAPI *)
(*   BhtSpec *)
(*   BtbAPI *)
(*   BtbSpec *)
(*   Fifo1API *)
(*   Fifo1Simulates *)
(*   Fifo1Spec *)
(*   MemoryAPI *)
(*   MemorySpec *)
(*   MultiplierAPI *)
(*   MultiplierSpec *)
(*   Rf *)
(*   RfScored *)
(*   PipelinedAPI *)
(*   PipelinedCommon. *)
(* From granite.app Require Fifo1Simulates MultiplierSimulates. *)
               
(* Set Primitive Projections. *)
(* Import RecordSetNotations. *)

(* (* Extensions: *)
(*    - generalize predictor  *)

(*    Ghost state: *)
(*    - function of method calls <-> trace *)

(*    Leakage driver: *)
(*    - Challenge: Decode stage can stall based on speculated instructions *)
(*    - Is speculated instruction memory ok? *)
(*  *) *)

(* Module CPU. *)
  
(*   Instance mulParams : MultiplierAPI.Params.Params :=  *)
(*     {| MultiplierAPI.Params.width := width; *)
(*        MultiplierAPI.Params.pfWidthNeZero := pfWidthNeZero *)
(*     |}.  *)
(*   Instance btbParams : Btb_sig := *)
(*     {| BtbAPI.idx_sz := 6; *)
(*        BtbAPI.tag_sz := width - 6; *)
(*        BtbAPI.addr_sz := width; *)
(*     |}. *)

(*   Instance bhtParams : Bht_sig := *)
(*     {| BhtAPI.idx_sz := 8; *)
(*        BhtAPI.addr_sz := width *)
(*     |}. *)
  
(*   Class ImplParams := *)
(*   { fifo1Spec: forall T, Inhabited T -> Fifo1Spec.SpecParams (Val := T) *)
(*   ; mulSpec : @MultiplierSpec.SpecParams mulParams *)
(*   ; bhtSpec: BhtSpec_sig *)
(*   ; btbSpec: BtbSpec_sig *)
(*   ; decode: mword -> decodedInst *)
(*   ; execALU: decodedInst -> mword -> mword -> mword *)
(*   ; memAddr : decodedInst -> mword -> mword *)
(*   ; execControl: decodedInst -> mword -> mword -> mword -> bool * mword (* pc, rval1, rval2 *) *)
(*   ; isMMIO: mword -> bool *)
(*   }. *)

(*   Section WithContext. *)
(*     Context {implParams: ImplParams}. *)
(*     (* Instance memParams : MemoryAPI.Params.Params := memParams.  *) *)
(*     Instance fifo1Params `{Inhabited T}: Fifo1Spec.SpecParams (Val := T) := *)
(*       fifo1Spec T _. *)
(*     Instance mulSpecParams : @MultiplierSpec.SpecParams mulParams := mulSpec. *)
(*     Instance btbSpecParams : BtbSpec_sig := btbSpec. *)
(*     Instance bhtSpecParams : BhtSpec_sig := bhtSpec. *)

(*     Inductive decodeResult := *)
(*     | DecodeStall *)
(*     | DecodeMispredict (pc: mword) *)
(*     | DecodeWrongIMemAddr (pc: mword) *)
(*     | DecodeProgress (pc: mword). *)

(*     Inductive executeResult := *)
(*     | ExecuteStall *)
(*     | ExecuteMispredict (pc: mword) *)
(*     | ExecuteProgress (pc: mword). *)


(*     #[projections(primitive=no)] *)
(*     Record GhostSt := *)
(*       { *)
(*         Ghost_fetchProgress : option mword; *)
(*         Ghost_decodeProgress : decodeResult; *)
(*         Ghost_executeProgress: executeResult; *)
(*         Ghost_writebackProgress: bool; *)
(*         (* Debug state *) *)
(*         Ghost_ncycles : nat ; *)
(*         Ghost_ninstr : nat ; *)
(*         Ghost_dbg_instrs : list e2w_bookkeeping *)
(*       }. *)
(*     Instance eta_GhostSt : Settable _ :=  *)
(*       settable! Build_GhostSt<Ghost_fetchProgress; Ghost_decodeProgress;  *)
(*                               Ghost_executeProgress; Ghost_writebackProgress; *)
(*                               Ghost_ncycles; Ghost_ninstr; Ghost_dbg_instrs>. *)
  
(*     Definition initialGhost : GhostSt :=  *)
(*       Build_GhostSt None DecodeStall ExecuteStall false 0 0 []. *)
  
(*     Notation rfScoredSpec := *)
(*       (rfScoredSpec (Val := mword) (initVal := bv_0 _)  *)
(*                                  (log_nregs := Params.log_nregs)). *)
  
(*     #[projections(primitive=no)] *)
(*     Record St :=  *)
(*       { Pc : mword *)
(*       ; Epoch : bit *)
(*       ; Depoch : bit *)
(*       ; Rf : State rfScoredSpec *)
(*       ; ToIMem : State (Fifo1Spec.spec (Val := mem_req_t)) *)
(*       ; ToDMem : State (Fifo1Spec.spec (Val := mem_req_t)) *)
(*       (* ; ToMMIO : State (Fifo1Spec.spec (Val := mem_req_t)) *) *)
(*       ; FromIMem : State (Fifo1Spec.spec (Val := mem_resp_t)) *)
(*       ; FromDMem : State (Fifo1Spec.spec (Val := mem_resp_t)) *)
(*       (* ; FromMMIO : State (Fifo1Spec.spec (Val := mem_resp_t)) *) *)
(*       ; F2d : State (Fifo1Spec.spec (Val := f2d_bookkeeping)) *)
(*       ; D2e : State (Fifo1Spec.spec (Val := d2e_bookkeeping)) *)
(*       ; E2w : State (Fifo1Spec.spec (Val := e2w_bookkeeping)) *)
(*       ; Mul : State MultiplierSpec.spec *)
(*       ; Bht : BhtSpec.St  *)
(*       ; Btb: BtbSpec.St *)
(*       }. *)
(*     Instance eta_St : Settable _ :=  *)
(*       settable! Build_St<Pc; Epoch; Depoch; Rf; ToIMem; ToDMem; (* ToMMIO; *) FromIMem; FromDMem; (* FromMMIO; *) F2d; D2e; E2w; Mul; Bht; Btb>. *)

(*     #[projections(primitive=no)] *)
(*     Record st_t := *)
(*       { base_st: St; *)
(*         ghost_st: GhostSt  *)
(*       }. *)
(*     Instance eta_st_t : Settable _ :=  *)
(*       settable! Build_st_t<base_st; ghost_st>. *)
(*     Coercion base_st : st_t >-> St. *)
  
(*     Definition initialSt (init_pc: mword) : St := *)
(*       {| Pc := init_pc *)
(*        ; Epoch := zeroes *)
(*        ; Depoch := zeroes *)
(*        ; Rf := initialState rfScoredSpec *)
(*        ; ToIMem := initialState Fifo1Spec.spec  *)
(*        ; ToDMem := initialState Fifo1Spec.spec  *)
(*        (* ; ToMMIO := initialState (Fifo1Spec.spec (Val := mem_req_t)) *) *)
(*        ; FromIMem := initialState Fifo1Spec.spec *)
(*        ; FromDMem := initialState Fifo1Spec.spec  *)
(*        (* ; FromMMIO := initialState (Fifo1Spec.spec (Val := mem_resp_t)) *) *)
(*        ; F2d := initialState Fifo1Spec.spec  *)
(*        ; D2e := initialState Fifo1Spec.spec  *)
(*        ; E2w := initialState Fifo1Spec.spec  *)
(*        ; Mul := initialState MultiplierSpec.spec *)
(*        ; Bht := BhtSpec.initial_st *)
(*        ; Btb := BtbSpec.initial_st *)
(*       |}. *)
(*     Definition initial_st (init_pc: mword) : st_t := *)
(*       {| base_st := initialSt init_pc; *)
(*          ghost_st := initialGhost  *)
(*       |}. *)
  
(*     Inductive BaseMethod : Type -> Type :=  *)
(*     | pc_ : forall {R}, Reg.ActionMethod mword R -> BaseMethod R *)
(*     | epoch_ : forall {R}, Reg.ActionMethod bit R -> BaseMethod R *)
(*     | depoch_ : forall {R}, Reg.ActionMethod bit R -> BaseMethod R *)
(*     | rf_ : forall {R}, RfScored.ActionMethod (Val := mword) (log_nregs := Params.log_nregs) R -> BaseMethod R *)
(*     | toIMem_ : forall {R}, Fifo1API.ActionMethod mem_req_t R -> BaseMethod R *)
(*     | ToDMem_ : forall {R}, Fifo1API.ActionMethod mem_req_t R -> BaseMethod R *)
(*     (* | toMMIO : forall {R}, Fifo1API.ActionMethod (Val := mem_req_t) R -> BaseMethod R *) *)
(*     | fromIMem_ : forall {R}, Fifo1API.ActionMethod mem_resp_t R -> BaseMethod R *)
(*     | fromDMem_ : forall {R}, Fifo1API.ActionMethod mem_resp_t R -> BaseMethod R *)
(*     (* | fromMMIO : forall {R}, Fifo1API.ActionMethod (Val := mem_resp_t) R -> BaseMethod R *) *)
(*     | f2d_ : forall {R}, Fifo1API.ActionMethod f2d_bookkeeping R -> BaseMethod R *)
(*     | d2e_ : forall {R}, Fifo1API.ActionMethod d2e_bookkeeping R -> BaseMethod R *)
(*     | e2w_ : forall {R}, Fifo1API.ActionMethod e2w_bookkeeping R -> BaseMethod R *)
(*     | mul_ : forall {R}, MultiplierAPI.ActionMethod R -> BaseMethod R *)
(*     | bht_ : forall {R}, BhtAPI.ActionMethod R -> BaseMethod R *)
(*     | btb_ : forall {R}, BtbAPI.ActionMethod R -> BaseMethod R *)
(*     | ghostUpdate : (st_t -> GhostSt) -> BaseMethod unit *)
(*     . *)
(*     Inductive BaseVMethod : Type -> Type :=  *)
(*     | pc : forall {R}, Reg.ValueMethod mword R -> BaseVMethod R *)
(*     | epoch : forall {R}, Reg.ValueMethod bit R -> BaseVMethod R *)
(*     | depoch : forall {R}, Reg.ValueMethod bit R -> BaseVMethod R *)
(*     | rf : forall {R}, RfScored.ValueMethod (Val := mword) (log_nregs := Params.log_nregs) R -> BaseVMethod R *)
(*     | toIMem : forall {R}, Fifo1API.ValueMethod mem_req_t R -> BaseVMethod R *)
(*     | toDMem : forall {R}, Fifo1API.ValueMethod mem_req_t R -> BaseVMethod R *)
(*     | fromIMem : forall {R}, Fifo1API.ValueMethod mem_resp_t R -> BaseVMethod R *)
(*     | fromDMem : forall {R}, Fifo1API.ValueMethod mem_resp_t R -> BaseVMethod R *)
(*     | f2d : forall {R}, Fifo1API.ValueMethod f2d_bookkeeping R -> BaseVMethod R *)
(*     | d2e : forall {R}, Fifo1API.ValueMethod d2e_bookkeeping R -> BaseVMethod R *)
(*     | e2w : forall {R}, Fifo1API.ValueMethod e2w_bookkeeping R -> BaseVMethod R *)
(*     | mul : forall {R}, MultiplierAPI.ValueMethod R -> BaseVMethod R *)
(*     | bht : forall {R}, BhtAPI.ValueMethod R -> BaseVMethod R *)
(*     | btb : forall {R}, BtbAPI.ValueMethod R -> BaseVMethod R *)
(*     . *)

(*     Notation "'BaseRegAction(' m ',' proj ',' st ')' " := *)
(*           (let '(v, mst') := Reg.EvalActionMethod m (proj%function (base_st st)) in *)
(*            (v, st <| base_st := (base_st st) <| proj := mst' |> |>)) (at level 100). *)
(*     Notation "'BaseRegValue(' m ',' proj ',' st ')' " := *)
(*           (Reg.EvalValueMethod m (proj%function (base_st st))) (at level 100, only parsing).  *)
(*     Notation "'BaseAction(' specFn ',' m ',' proj ',' st ')' " := *)
(*         (let '(v, mst') := EvalMethod specFn m (proj%function (base_st st)) in *)
(*          (v, st <| base_st := (base_st st) <| proj := mst' |> |>)) (at level 100, only parsing). *)
(*     Notation "'BaseValue(' spec ',' m ',' proj ',' st ')' " := *)
(*         (EvalVMethod spec m (proj%function (base_st st))) (at level 100, only parsing). *)
(*     Definition evalBaseVMethod {A} (m: BaseVMethod A) (st: st_t) : A := *)
(*       let base := st.(base_st) in  *)
(*       match m with *)
(*       | pc m => BaseRegValue(m, Pc, st) *)
(*       | epoch m => BaseRegValue(m, Epoch, st) *)
(*       | depoch m => BaseRegValue(m, Depoch, st) *)
(*       | rf m => BaseValue(rfScoredSpec, m, Rf, st) *)
(*       | toIMem m => BaseValue(Fifo1Spec.spec, m, ToIMem, st) *)
(*       | toDMem m => BaseValue(Fifo1Spec.spec, m, ToDMem, st) *)
(*       | fromIMem m => BaseValue(Fifo1Spec.spec, m, FromIMem, st) *)
(*       | fromDMem m => BaseValue(Fifo1Spec.spec, m, FromDMem, st) *)
(*       | f2d m => BaseValue(Fifo1Spec.spec, m, F2d, st) *)
(*       | d2e m => BaseValue(Fifo1Spec.spec, m, D2e, st) *)
(*       | e2w m => BaseValue(Fifo1Spec.spec, m, E2w, st) *)
(*       | mul m => BaseValue(MultiplierSpec.spec, m, Mul, st) *)
(*       | bht m => BaseValue(BhtSpec.spec, m, Bht, st) *)
(*       | btb m => BaseValue(BtbSpec.spec, m, Btb, st) *)
(*       end.  *)

(*     Definition evalBaseMethod {A} (m: BaseMethod A) (st: st_t) : A * st_t := *)
(*       let base := st.(base_st) in  *)
(*       match m with *)
(*       | pc_ m => BaseRegAction(m, Pc, st) *)
(*       | epoch_ m => BaseRegAction(m, Epoch, st) *)
(*       | depoch_ m => BaseRegAction(m, Depoch, st) *)
(*       | rf_ m => BaseAction(rfScoredSpec, m, Rf, st) *)
(*       | toIMem_ m => BaseAction(Fifo1Spec.spec, m, ToIMem, st) *)
(*       | ToDMem_ m => BaseAction(Fifo1Spec.spec, m, ToDMem, st) *)
(*       | fromIMem_ m => BaseAction(Fifo1Spec.spec, m, FromIMem, st) *)
(*       | fromDMem_ m => BaseAction(Fifo1Spec.spec, m, FromDMem, st) *)
(*       | f2d_ m => BaseAction(Fifo1Spec.spec, m, F2d, st) *)
(*       | d2e_ m => BaseAction(Fifo1Spec.spec, m, D2e, st) *)
(*       | e2w_ m => BaseAction(Fifo1Spec.spec, m, E2w, st) *)
(*       | mul_ m => BaseAction(MultiplierSpec.spec, m, Mul, st) *)
(*       | bht_ m => BaseAction(BhtSpec.spec, m, Bht, st) *)
(*       | btb_ m => BaseAction(BtbSpec.spec, m, Btb, st) *)
(*       | ghostUpdate fn => *)
(*           ((), st <| ghost_st := fn st |>)  *)
(*       end.  *)
  
(*     Definition base (init_pc: mword) : Spec _ _ :=  *)
(*       {| State := st_t; *)
(*          EvalVMethod A := evalBaseVMethod; *)
(*          EvalMethod A := evalBaseMethod; *)
(*          initialState := initial_st init_pc|}. *)
  
(*     Notation fifo1_first := Fifo1API.First. *)
(*     Notation fifo1_empty := Fifo1API.Empty. *)
(*     Notation fifo1_full := Fifo1API.Full. *)
(*     Notation fifo1_deq := Fifo1API.Deq. *)
(*     Notation fifo1_enq := Fifo1API.Enq. *)
 
(*     Definition toMem (mem: mem_type) {T} := *)
(*        match mem with *)
(*        | IMEM => @toIMem T *)
(*        | DMEM => @toDMem T *)
(*        end. *)
(*     Definition fromMem (mem: mem_type) {T} := *)
(*        match mem with *)
(*        | IMEM => @fromIMem T *)
(*        | DMEM => @fromDMem T *)
(*        end. *)
(*     Definition toMem_ (mem: mem_type) {T} := *)
(*        match mem with *)
(*        | IMEM => @toIMem_ T *)
(*        | DMEM => @ToDMem_ T *)
(*        end. *)
(*     Definition fromMem_ (mem: mem_type) {T} := *)
(*        match mem with *)
(*        | IMEM => @fromIMem_ T *)
(*        | DMEM => @fromDMem_ T *)
(*        end. *)

(*     Notation prog := (prog BaseVMethod BaseMethod). *)
(*     Notation expr := (expr BaseVMethod). *)

(*     Open Scope expr_scope.                                        *)

(*     Definition peek_req mem : expr mem_req_t := *)
(*       v ← (toMem mem) fifo1_first; *)
(*       return v. *)
  
(*     Definition can_deq_req (mem: mem_type): expr bool := *)
(*       empty ← (toMem mem) fifo1_empty; *)
(*       return (negb empty). *)
  
(*     Definition can_enq_resp (mem: mem_type): expr bool := *)
(*       full ← (fromMem mem) fifo1_full; *)
(*       return (negb full). *)
(*     Close Scope expr_scope. *)
(*     Open Scope prog_scope. *)
  
(*     Definition enq_resp (mem: mem_type) (arg: mem_resp_t) : prog unit := *)
(*       (fromMem_ mem) (fifo1_enq arg);; *)
(*       pass. *)
  
(*     Definition deq_req (mem: mem_type): prog unit := *)
(*       (toMem_ mem) fifo1_deq;; *)
(*       pass. *)
  
(*     (* Definition predictPC (pc: mword) : Prog BaseMethod mword := *) *)
(*     (*     bv_add pc (of_Z width 1). *) *)
  
(*     Definition fetch_stage : prog (option mword) := *)
(*       toIMem_full ← toIMem fifo1_full; *)
(*       f2d_full ← f2d fifo1_full; *)
(*       if toIMem_full || f2d_full then *)
(*         return None  *)
(*       else *)
(*         _pc ← pc Reg.Read; *)
(*         _epoch ← epoch Reg.Read; *)
(*         _depoch ← depoch Reg.Read; *)
(*         ppc ← btb (BtbAPI.PredPc _pc); *)
(*         (* let ppc := predictPC _pc in  *) *)
(*         pc_ (Reg.Write ppc);; *)
(*         toIMem_ (fifo1_enq {| mem_req_is_store := false; (* load *) *)
(*                               mem_req_addr := _pc; *)
(*                               mem_req_data := zeroes |});; *)
(*         f2d_ (fifo1_enq {| f2d_pc := _pc; *)
(*                            f2d_ppc := ppc; *)
(*                            f2d_epoch := _epoch; *)
(*                            f2d_depoch := _depoch; *)
(*                         |});; *)
(*         return (Some _pc).  *)

(*     (* Return true if dequeue from IMem *) *)
(*     Definition decode_stage : prog decodeResult := *)
(*       fromIMem_empty ← fromIMem fifo1_empty; *)
(*       f2d_empty ← f2d fifo1_empty; *)
(*       d2e_full ← d2e fifo1_full; *)
(*       imem_resp ← fromIMem fifo1_first; *)
(*       f2d_book ← f2d fifo1_first; *)
(*       _epoch ← epoch Reg.Read; *)
(*       _depoch ← depoch Reg.Read; *)
(*       let dinst := decode imem_resp.(mem_resp_data) in *)
(*       if fromIMem_empty || f2d_empty then *)
(*         return DecodeStall (* Nothing to do *) *)
(*       else if bool_decide (imem_resp.(mem_resp_addr) = f2d_book.(f2d_pc)) then *)
(*         if bool_decide (f2d_book.(f2d_epoch) = _epoch) && *)
(*            bool_decide (f2d_book.(f2d_depoch) = _depoch) then *)
(*         let rs1_idx := dinst.(dInst_rs1) in  *)
(*         let rs2_idx := dinst.(dInst_rs2) in  *)
(*         let rd_idx := dinst.(dInst_rd) in *)
(*         locked1 ← rf (RfScored.IsLocked rs1_idx);   *)
(*         locked2 ← rf (RfScored.IsLocked rs2_idx);   *)
(*         locked_rd ← rf (RfScored.IsLocked rd_idx); (* TODO: remove this *) *)
(*         if d2e_full || (locked1 || locked2 || locked_rd) then *)
(*           return DecodeStall (* Stall *) *)
(*         else  *)
(*           rs1 ← rf (RfScored.Read rs1_idx); *)
(*           rs2 ← rf (RfScored.Read rs2_idx); *)
(*           let imm := dinst.(dInst_imm) in  *)
(*           bht_ppcDP ← bht (BhtAPI.PpcDP f2d_book.(f2d_pc) (bv_add f2d_book.(f2d_pc) (bv_zero_extend _ imm))); *)
(*           (* TODO; jal  *) *)
(*           let isControl := bool_decide (dinst.(dInst_opcode) = ToyISA.ISA.Encoding.opcode_Beq) in *)
(*           let ppcDP := if isControl then bht_ppcDP else f2d_book.(f2d_ppc) in *)
(*           let dbook := {| d2e_rval1 := rs1; *)
(*                           d2e_rval2 := rs2; *)
(*                           d2e_pc := f2d_book.(f2d_pc); *)
(*                           d2e_ppc := ppcDP; *)
(*                           d2e_epoch := f2d_book.(f2d_epoch); *)
(*                           d2e_inst := imem_resp.(mem_resp_data); *)
(*                        |} in *)
(*           f2d_ fifo1_deq;; *)
(*           fromIMem_ fifo1_deq;; *)
(*           d2e_ (fifo1_enq dbook);; *)
(*           callProg (if (bool_decide (ppcDP = f2d_book.(f2d_ppc))) then *)
(*                       pass  *)
(*                     else *)
(*                       pc_ (Reg.Write ppcDP);; *)
(*                       depoch_ (Reg.Write (bv_not _depoch));; *)
(*                       pass); *)
(*           if dinst.(dInst_rdValid) then (* NB: r0 invalid *) *)
(*             rf_ (RfScored.AcquireLock rd_idx);; *)
(*             return (DecodeProgress f2d_book.(f2d_pc)) *)
(*           else *)
(*             return (DecodeProgress f2d_book.(f2d_pc)) *)
(*         else (* Mispredicted *) *)
(*           f2d_ fifo1_deq;; *)
(*           fromIMem_ fifo1_deq;; *)
(*           return (DecodeMispredict f2d_book.(f2d_pc))   *)
(*       else (* Drop IMem *) *)
(*         fromIMem_ fifo1_deq;; *)
(*         return (DecodeWrongIMemAddr f2d_book.(f2d_pc)). *)

(*     Definition execute_stage (leakage: option instr_leak_t): prog executeResult := *)
(*       d2e_empty ← d2e fifo1_empty; *)
(*       e2w_full ← e2w fifo1_full; *)
(*       d2e_book ← d2e fifo1_first; *)
(*       _epoch ← epoch Reg.Read; *)
(*       (* Use instruction from leakage trace, if provided *) *)
(*       let inst := d2e_book.(d2e_inst) in  *)
(*       let _pc := d2e_book.(d2e_pc) in *)
(*       let dinst := decode inst in  *)
(*       if (d2e_empty:bool) then *)
(*         Return ExecuteStall (* Nothing to do *) *)
(*       else if bool_decide (d2e_book.(d2e_epoch) = _epoch) then *)
(*         (* Correct path *) *)
(*         let rval1 := d2e_book.(d2e_rval1) in *)
(*         let rval2 := d2e_book.(d2e_rval2) in *)
(*         let output_alu := execALU dinst d2e_book.(d2e_rval1) d2e_book.(d2e_rval2) in *)
(*         (* Use nextPC from leakage trace, if provided *) *)
(*         let '(taken, nextPC) :=  *)
(*           from_option (fun s => (leak_taken s, leak_nextPC s)) *)
(*             (execControl dinst _pc d2e_book.(d2e_rval1) d2e_book.(d2e_rval2))  *)
(*             leakage in *)
(*         let ex_book := {| e2w_output_alu := output_alu; *)
(*                           e2w_inst := inst *)
(*                        |} in  *)
(*         toDMem_full ← toDMem fifo1_full; *)
(*         mul_full ← mul MultiplierAPI.Full; *)
(*         if   e2w_full  *)
(*            || (isMemory dinst.(dInst_type) && toDMem_full)  *)
(*            || (isMul dinst.(dInst_type) && mul_full) then *)
(*           (* Stall *) *)
(*           Return ExecuteStall *)
(*         else *)
(*           callProg (if isMemory dinst.(dInst_type) then *)
(*                  (* Use dmem address from leakage trace, if provided *) *)
(*                   let addr :=  *)
(*                     from_option ((default zeroes) ∘ leak_dmem_addr) *)
(*                       (memAddr dinst rval1)  *)
(*                       leakage in  *)
(*                   let req := *)
(*                     if isStore dinst.(dInst_type) then *)
(*                       {| mem_req_is_store := true; *)
(*                          mem_req_addr := addr; *)
(*                          mem_req_data := rval2 *)
(*                       |} *)
(*                     else  *)
(*                       {| mem_req_is_store := false; *)
(*                          mem_req_addr := addr; *)
(*                          mem_req_data := zeroes *)
(*                       |} in *)
(*                     ToDMem_ (fifo1_enq req);; *)
(*                     pass *)
(*                 else if isMul dinst.(dInst_type) then *)
(*                   let mul_arg := *)
(*                     match leakage with *)
(*                     | Some leakage => *)
(*                         if default false leakage.(leak_mul_zero) then *)
(*                           {| input_a := zeroes; input_b := zeroes |} *)
(*                         else *)
(*                           {| input_a := of_Z _ 1; input_b := of_Z _ 1|} *)
(*                     | None => {| input_a := rval1; input_b := rval2 |} *)
(*                     end in  *)
(*                   mul_ (MultiplierAPI.Enq mul_arg);; *)
(*                   pass *)
(*                 else pass *)
(*                 ); *)
(*           callProg (if bool_decide (nextPC = d2e_book.(d2e_ppc)) then *)
(*                    pass (* Correct prediction *) *)
(*                  else (* Mispredicted *) *)
(*                    epoch_ (Reg.Write (bv_not _epoch));; *)
(*                    pc_ (Reg.Write nextPC);; *)
(*                    btb_ (BtbAPI.Update _pc nextPC);; *)
(*                    pass *)
(*                 ); *)
(*           let isControl := bool_decide (dinst.(dInst_opcode) = ToyISA.ISA.Encoding.opcode_Beq) in *)
(*           callProg (if isControl then *)
(*                   bht_ (BhtAPI.Update _pc taken);; *)
(*                   pass *)
(*                  else pass); *)
(*           d2e_ fifo1_deq;; *)
(*           e2w_ (fifo1_enq ex_book);; *)
(*           return (ExecuteProgress _pc) *)
(*       else (* Mispredicted *) *)
(*         d2e_ fifo1_deq;; *)
(*         if dinst.(dInst_rdValid) then (* Release any write lock *) *)
(*           rf_ (RfScored.ReleaseLock dinst.(dInst_rd));; *)
(*           return (ExecuteMispredict _pc) *)
(*         else *)
(*           return (ExecuteMispredict _pc). *)
(*     Definition writeback_stage : prog bool := *)
(*       e2w_empty ← e2w fifo1_empty; *)
(*       e2w_book ← e2w fifo1_first; *)
(*       let dinst := decode e2w_book.(e2w_inst) in  *)
(*       if (e2w_empty: bool) then *)
(*         return false (* Nop *) *)
(*       else *)
(*         let isLoad := isLoad dinst.(dInst_type) in  *)
(*         let isMul := isMul dinst.(dInst_type) in  *)
(*         fromDMem_empty ← fromDMem fifo1_empty; *)
(*         frommul_ready ← mul MultiplierAPI.RespReady; *)
(*         if (isLoad && fromDMem_empty) || *)
(*            (isMul && negb frommul_ready) then *)
(*           (* Response not ready *) *)
(*           return false *)
(*         else  *)
(*           let/prog data :=  *)
(*                    (if isLoad then *)
(*                      resp ← fromDMem fifo1_first; *)
(*                      fromDMem_ fifo1_deq;; *)
(*                      Return resp.(mem_resp_data) *)
(*                    else if isMul then *)
(*                      resp ← mul MultiplierAPI.Peek; *)
(*                      mul_ MultiplierAPI.Deq;; *)
(*                      Return (bv_extract 0 width resp) *)
(*                    else *)
(*                      Return e2w_book.(e2w_output_alu) *)
(*                    ) in  *)
(*           e2w_ fifo1_deq;; *)
(*           ghostUpdate (fun st => st.(ghost_st) <| Ghost_ninstr ::= S |> *)
(*                                             <| Ghost_dbg_instrs ::= cons e2w_book |>  *)
(*                       );; *)
(*           if dinst.(dInst_rdValid) then *)
(*             rf_ (RfScored.WriteAndRelease dinst.(dInst_rd) data);;   *)
(*             return true *)
(*           else *)
(*             return true. *)
  
(*     Definition tick (opt_leakage: option instr_leak_t): prog unit := *)
(*       let/prog wb_progress := writeback_stage in  *)
(*       let/prog ex_progress := execute_stage opt_leakage in *)
(*       let/prog de_progress := decode_stage in *)
(*       let/prog fe_progress := fetch_stage in *)
(*       mul_ MultiplierAPI.Tick;; *)
(*       ghostUpdate (fun st => st.(ghost_st) <| Ghost_ncycles ::= S |> *)
(*                                         <| Ghost_fetchProgress := fe_progress |> *)
(*                                         <| Ghost_decodeProgress := de_progress |> *)
(*                                         <| Ghost_executeProgress := ex_progress |> *)
(*                                         <| Ghost_writebackProgress := wb_progress |>  *)
(*                   );; *)
(*       pass. *)
  
(*     Definition impl_VM [R] (m: ValueMethod R) : expr R := *)
(*       match m with *)
(*       | CanEnqResp mem => can_enq_resp mem *)
(*       | CanDeqReq mem => can_deq_req mem *)
(*       | Peek mem => peek_req mem *)
(*       end. *)
  
(*     Definition impl_AM [R] (m: ActionMethod R) : prog R := *)
(*       match m with *)
(*       | EnqResp mem arg => enq_resp mem arg  *)
(*       | DeqReq mem => deq_req mem *)
(*       | Tick => tick None *)
(*       end. *)
  
(*     Definition cpu (init_pc: mword) := object (base init_pc) impl_VM impl_AM. *)
(*     Definition cpu_spec (init_pc: mword) := coarsen (cpu init_pc). *)
(*   End WithContext. *)
(* End CPU. *)


