(* From stdpp Require Import base finite nmap. *)
(* From stdpp.bitvector Require Import definitions. *)
(* From RecordUpdate Require Import RecordSet. *)
(* From granite.core Require Import *)
(*   Bits  *)
(*   Object *)
(*   Program  *)
(*   ProgramOps. *)

(* From granite.app Require Import  *)
(*   MemoryAPI *)
(*   Pipelined *)
(*   PipelinedCommon *)
(*   PipelinedAPI *)
(*   TopAPI *)
(*   TopImpl. *)
(* Set Primitive Projections. *)
(* Import RecordSetNotations. *)

(* Import CPU. *)

(* Section WithContext. *)
(*   Context {implParams: CPU.ImplParams}. *)
(*   Instance memParams : MemoryAPI.Params.Params := memParams.  *)
(*   Context (imemParams: MemorySpec.SpecParams). *)
(*   Context (dmemParams: MemorySpec.SpecParams). *)
(*   Context {mmioParams: MMIO.SpecParams}. *)
(*   Context (init_pc: mword) *)
(*           (init_imem init_dmem: MemorySpec.memory_t). *)

(*   #[projections(primitive=no)] *)
(*   Record st_t :=  *)
(*   { Cpu: Pipelined.CPU.st_t *)
(*   ; Imem: MemorySpec.st_t *)
(*   ; Dmem: MemorySpec.st_t *)
(*   ; Mmio: MMIO.st_t *)
(*   }. *)
(*   Instance eta_st_t : Settable _ := settable! Build_st_t<Cpu; Imem; Dmem; Mmio>. *)

(*   Definition initial_st : st_t := *)
(*     {| Cpu := CPU.initial_st init_pc; *)
(*        Imem := MemorySpec.initial_st init_imem; *)
(*        Dmem := MemorySpec.initial_st init_dmem; *)
(*        Mmio := MMIO.initial_st  *)
(*     |}. *)

(*   Definition evalBaseMethod {A} (m: TopImpl.BaseMethod A) (st: st_t) : A * st_t := *)
(*     match m with *)
(*     | TopImpl.cpu_ m => Action(cpu_spec init_pc, m, Cpu, st) *)
(*     | TopImpl.imem_ m => *)
(*         Action(MemorySpec.spec (specParams := imemParams) init_imem, m, Imem, st) *)
(*     | TopImpl.dmem_ m => *)
(*         Action(MemorySpec.spec (specParams := dmemParams) init_dmem, m, Dmem, st) *)
(*     | TopImpl.mmio_ m => *)
(*         Action(MMIO.spec (specParams := mmioParams), m, Mmio, st) *)
(*     end. *)

(*   Definition evalBaseVMethod {A} (m: TopImpl.BaseVMethod A) (st: st_t) : A := *)
(*     match m with *)
(*     | TopImpl.cpu m => Value(cpu_spec init_pc, m, Cpu, st) *)
(*     | TopImpl.imem m => *)
(*         Value(MemorySpec.spec (specParams := imemParams) init_imem, m, Imem, st) *)
(*     | TopImpl.dmem m => *)
(*         Value(MemorySpec.spec (specParams := dmemParams) init_dmem, m, Dmem, st) *)
(*     | TopImpl.mmio m => *)
(*         Value(MMIO.spec (specParams := mmioParams), m, Mmio, st) *)
(*     end. *)
(*   Definition base : Spec _ _ :=  *)
(*     {| State := st_t; *)
(*        EvalVMethod A := evalBaseVMethod; *)
(*        EvalMethod A := evalBaseMethod; *)
(*        initialState := initial_st *)
(*     |}. *)

(*   Definition top := object base (TopImpl.impl_VM) (TopImpl.impl_AM isMMIO). *)
(*   Definition top_spec := coarsen top. *)

(*   Definition step_n (n: nat) : Program.prog TopAPI.VMethod TopAPI.Method unit := *)
(*     seqPrograms (map (fun _ => CallMet TopAPI.Tick (fun _ => pass)) (seq 0 n)) pass. *)

(* End WithContext. *)
