(* From stdpp Require Import base finite nmap. *)
(* From stdpp.bitvector Require Import definitions. *)
(* From RecordUpdate Require Import RecordSet. *)
(* From granite.core Require Import *)
(*   Bits  *)
(*   Object *)
(*   Program  *)
(*   ProgramOps *)
(*   Tactics. *)

(* From granite.app Require Import  *)
(*   BhtAPI *)
(*   BhtSpec *)
(*   BhtSimulates *)
(*   BtbAPI *)
(*   BtbSpec *)
(*   BtbSimulates *)
(*   MemoryAPI *)
(*   MemorySpec *)
(*   Pipelined *)
(*   PipelinedCommon *)
(*   PipelinedSimulates *)
(*   Rf *)
(*   ToyIsaMachine *)
(*   ToyIsaMachineTop. *)
                 
(* Set Primitive Projections. *)
(* Import RecordSetNotations. *)


(* Module TestToyIsaMachine. *)
(*   Import ToyISA. *)
(*   Definition mk_imem {T} (prog: list T) : Nmap T := *)
(*     list_to_map (imap (fun i a => (N.of_nat i, a)) prog). *)

(*   (* Dummy params *) *)
(*   Instance mulParams : Multiplier.MultiplierParams := *)
(*     { logNSteps := 1 }. *)
(*   (* Instance implParams : CPU.ImplParams := *) *)
(*   (*   {| CPU.fifo1Spec := fun T _ => @Fifo1Simulates.specParams T inhabitant; *) *)
(*   (*      CPU.mulSpec := MultiplierSimulates.multiplierParams; *) *)
(*   (*      CPU.decode := decode; *) *)
(*   (*      CPU.execALU := execALU; *) *)
(*   (*      CPU.memAddr := memAddr; *) *)
(*   (*      CPU.execControl := fun inst pc rval1 rval2 => fst (execControl inst pc rval2 rval2) *) *)
(*   (*   |}.                 *) *)
(*   Instance memParams : MemoryAPI.Params.Params :=  *)
(*     {| MemoryAPI.Params.width := width |}. *)

(*   Instance memSpecParams: MemorySpec.SpecParams := *)
(*     {| MemorySpec.default_peek := fun _ => inhabitant; *)
(*        MemorySpec.resp_ready := fun _ => true; *)
(*        MemorySpec.is_full := fun _ => false *)
(*     |}. *)

(*   Instance mmioParams : MMIO.SpecParams := *)
(*     {| MMIO.peek := fun _ => {| mem_resp_addr := bv_0 _; *)
(*                              mem_resp_data := bv_0 _ |}; *)
(*        MMIO.resp_ready := fun _ => false; *)
(*        MMIO.full := fun _ => false *)
(*     |}. *)


(*   Lemma _pfDecodeOk :  *)
(*     ∀ inst : mword, dInst_type (PipelinedCommon.decode inst) = MemInstr true *)
(*                    → dInst_rdValid (PipelinedCommon.decode inst) = false. *)
(*   Proof. *)
(*     intros. unfold PipelinedCommon.decode in *; cbn in *. *)
(*     repeat match goal with *)
(*     | |- bool_decide _ = false => *)
(*         apply bool_decide_eq_false  *)
(*     | H: context[bool_decide _] |- _ => case_bool_decide *)
(*     | H : bv_extract ?x ?y ?z  = _ |- context[bv_extract ?x ?y ?z] => rewrite H *)
(*     end. *)
(*     all: unfold not; intros hcase; split_ors_in hcase; done. *)
(*   Qed. *)

(*   Instance isaParams : ToyIsaMachine.IsaParams :=  *)
(*     {| decode := PipelinedCommon.decode; *)
(*        pfDecodeOk := _pfDecodeOk; *)
(*        execALU := PipelinedCommon.execALU; *)
(*        memAddr := PipelinedCommon.memAddr; *)
(*        execControl := PipelinedCommon.execControl; *)
(*        isMMIO := fun _ => false; *)
(*     |}. *)

(*   Instance imemParams: MemorySpec.SpecParams := memSpecParams. *)
(*   Instance dmemParams: MemorySpec.SpecParams := memSpecParams. *)


(*   Instance mulSpecParams : @MultiplierSpec.SpecParams CPU.mulParams :=  *)
(*     MultiplierSimulates.multiplierParams. *)
(*   Instance btbParams : Btb_sig := *)
(*     {| BtbAPI.idx_sz := 6; *)
(*        BtbAPI.tag_sz := width - 6; *)
(*        BtbAPI.addr_sz := width; *)
(*     |}. *)

(*   Instance bhtParams : Bht_sig := *)
(*     {| BhtAPI.idx_sz := 8; *)
(*        BhtAPI.addr_sz := width *)
(*     |}. *)

(*   Instance bhtSpecParams : BhtSpec.BhtSpec_sig := BhtSimulates.BhtSpecParams. *)
(*   Instance btbSpecParams : BtbSpec.BtbSpec_sig := BtbSimulates.BtbSpecParams. *)

(*   Instance specParams (init_pc: mword) : ToyIsaMachine.SpecParams := *)
(*     @PipelinedSimulates.specParams init_pc isaParams mulSpecParams  *)
(*                                    bhtSpecParams btbSpecParams *)
(*       (fun T _ => @Fifo1Simulates.specParams T inhabitant). *)

(*   Module ArithTest. *)

(*     Definition imem_prog := ISA.Encoding.compile_prog ArithTest.prog__double. *)
(*     Definition dmem_init : MemorySpec.memory_t := ∅. *)

(*     Definition top_spec :=  *)
(*       let initPc := zeroes in  *)
(*       let imem := mk_imem imem_prog in  *)
(*       let dmem := dmem_init in  *)
(*       @ToyIsaMachineTop.top_spec isaParams (specParams initPc) mmioParams *)
(*                                  initPc imemParams dmemParams *)
(*                                  imem dmem. *)
                                 
(*     Definition test_double n := *)
(*       evalProg top_spec (ToyIsaMachineTop.step_n n) (initialState top_spec). *)

(*     Open Scope isa_scope. *)
(*     Import ISA. *)

(*     Notation prog := (prog ToyIsaMachine.BaseVMethod ToyIsaMachine.BaseMethod). *)


(*     Definition test_double_ok :=  *)
(*       let '(_, st) := test_double 22 in *)
(*       let prog : prog _ := *)
(*         {{ v_x1 ← ToyIsaMachine.rf (Rf.Read x.1); *)
(*            v_x2 ← ToyIsaMachine.rf (Rf.Read x.2); *)
(*            v_x3 ← ToyIsaMachine.rf (Rf.Read x.3); *)
(*            return (v_x1, v_x2, v_x3) }} in *)
(*       let '((v_x1, v_x2, v_x3), _) := evalProg (ToyIsaMachine.base zeroes)  *)
(*                                           prog st.(ToyIsaMachineTop.Cpu) in *)
      
(*       ((bool_decide (v_x1 = 3%bv ) *)
(*          && (bool_decide (v_x2 = 6%bv)) *)
(*          && (bool_decide (v_x3 = 9%bv)) *)
(*         )). *)

(*     Goal test_double_ok = true. *)
(*     Proof. vm_compute; reflexivity. Qed. *)

(*     Definition test_double_fail := (@eq_refl _ false) : *)
(*       let '(_, st) := test_double 10 in *)
(*       let prog : prog _ := *)
(*         {{ v_x1 ← ToyIsaMachine.rf (Rf.Read x.1); *)
(*            return v_x1 }} in *)
(*       let '((v_x1, _)) := evalProg (ToyIsaMachine.base zeroes)  *)
(*                                           prog st.(ToyIsaMachineTop.Cpu ) in *)
(*       (bool_decide (v_x1 = 2%bv)) = false. *)

(*   End ArithTest. *)

(*   Module FibTest. *)
(*     Definition imem_prog := ISA.Encoding.compile_prog MemTest.prog__fib. *)
(*     Definition dmem_init : MemorySpec.memory_t := ∅. *)

(*     Definition top_spec := *)
(*       let initPc := zeroes in *)
(*       let imem := mk_imem imem_prog in *)
(*       let dmem := dmem_init in *)
(*       @ToyIsaMachineTop.top_spec isaParams (specParams initPc) mmioParams *)
(*                                  initPc imemParams dmemParams *)
(*                                  imem dmem. *)
(*     Definition test_fib n := *)
(*       evalProg top_spec (ToyIsaMachineTop.step_n n) (initialState top_spec). *)

(*     Open Scope isa_scope. *)
(*     Import ISA. *)
(*     Notation prog := (prog ToyIsaMachine.BaseVMethod ToyIsaMachine.BaseMethod). *)

(*     (* Eval vm_compute in (test_fib 20). *) *)
(*     Definition test_fib_ok := *)
(*       let '(_, st) := test_fib 20 in *)
(*       let dmem := st.(ToyIsaMachineTop.Dmem ).(MemorySpec.base).(MemorySpec.mem) in *)
(*       let v0 := dmem !! 0%N in *)
(*       let v1 := dmem !! 1%N in *)
(*       let v2 := dmem !! 2%N in *)
(*       (* let v3 := dmem !! 3%N in *) *)
(*       (* let v4 := dmem !! 4%N in *) *)
(*       (* let v5 := dmem !! 5%N in *) *)
(*       (* let v6 := dmem !! 6%N in *) *)
(*       (bool_decide (v0 = Some 0%bv /\ *)
(*                    v1 = Some 1%bv /\ *)
(*                    v2 = Some 1%bv )). *)
(*                    (* v3 = Some 2%bv /\ *) *)
(*                    (* v4 = Some 3%bv /\ *) *)
(*                    (* v5 = Some 5%bv /\ *) *)
(*                    (* v6 = Some 8%bv)). *) *)
(*     Goal test_fib_ok = true. *)
(*     Proof.  *)
(* vm_compute; reflexivity. Qed. *)
(*   End FibTest. *)

(*   (* Module SecretTest. *) *)
(*   (*   Definition imem_prog := ISA.Encoding.compile_prog MemTest.prog__fib. *) *)
(*   (*   Definition dmem_init : MemorySpec.memory_t := ∅. *) *)

(*   (*   Definition top_spec :=  *) *)
(*   (*     let initPc := zeroes in  *) *)
(*   (*     let imem := mk_imem imem_prog in  *) *)
(*   (*     let dmem := dmem_init in  *) *)
(*   (*     @ToyIsaMachineTop.top_spec isaParams (specParams initPc) *) *)
(*   (*                                initPc imemParams dmemParams *) *)
(*   (*                                imem dmem. *) *)
(*   (*   Definition test_fib n := *) *)
(*   (*     evalProg top_spec (ToyIsaMachineTop.step_n n) (initialState top_spec). *) *)

(*   (*   Open Scope isa_scope. *) *)
(*   (*   Import ISA. *) *)

(*   (*   Definition test_fib_ok :=   *) *)
(*   (*     let '(_, st) := test_fib 60 in *) *)
(*   (*     let dmem := st.(ToyIsaMachineTop.Dmem zeroes).(MemorySpec.base).(MemorySpec.mem) in *) *)
(*   (*     let v0 := dmem !! 0%N in *) *)
(*   (*     let v1 := dmem !! 1%N in *) *)
(*   (*     let v2 := dmem !! 2%N in *) *)
(*   (*     let v3 := dmem !! 3%N in *) *)
(*   (*     let v4 := dmem !! 4%N in *) *)
(*   (*     let v5 := dmem !! 5%N in *) *)
(*   (*     let v6 := dmem !! 6%N in *) *)
(*   (*     (bool_decide (v0 = Some 0%bv /\ *) *)
(*   (*                  v1 = Some 1%bv /\ *) *)
(*   (*                  v2 = Some 1%bv /\ *) *)
(*   (*                  v3 = Some 2%bv /\ *) *)
(*   (*                  v4 = Some 3%bv /\ *) *)
(*   (*                  v5 = Some 5%bv /\ *) *)
(*   (*                  v6 = Some 8%bv)). *) *)
(*   (*   Goal test_fib_ok = true. *) *)
(*   (*   Proof. vm_compute; reflexivity. Qed. *) *)
(*   (* End FibTest. *) *)

(* End TestToyIsaMachine. *)

