(* From stdpp Require Import base finite nmap strings. *)
(* From stdpp.bitvector Require Import definitions. *)
(* From RecordUpdate Require Import RecordSet. *)

(* From granite.core Require Import *)
(*   Bits *)
(*   Object *)
(*   Program *)
(*   ProgramOps *)
(*   Reg. *)

(* From granite.app Require Import *)
(*   Fifo1API *)
(*   Fifo1Spec *)
(*   LoadBufferAPI *)
(*   LoadBufferSpec *)
(*   MemoryAPI *)
(*   PipelinedCommon *)
(*   Rf *)
(*   PipelinedAPI. *)

(* Set Primitive Projections. *)
(* Import RecordSetNotations. *)

(* (* Instance memParams : MemoryAPI.Params.Params := memParams.  *) *)


(* (* Processor can issue speculative loads --> load buffer. *)
(*    Keep track of outgoing load requests to an address *)
   
(*    For now, let's assume no memory load speculation. *)
(*  *)  *)

(* Class IsaParams := *)
(* { decode: mword -> decodedInst *)
(* ; pfDecodeOk: forall inst, dInst_type (decode inst) = MemInstr true -> *)
(*                       dInst_rdValid (decode inst) = false *)
(* ; execALU: decodedInst -> mword -> mword -> mword *)
(* ; memAddr : decodedInst -> mword -> mword *)
(* ; execControl: decodedInst -> mword -> mword -> mword -> bool * mword (* pc, rval1, rval2 *) *)
(* ; isMMIO: mword -> bool *)
(* }. *)

(* Inductive StepT := *)
(* | LoadInstr (addr: mword) (* issue an imem load *) *)
(* | RecvIMemResp (keep: bool) (* receive an imem resp *) *)
(* | DowngradeIMem (addr: mword) (* downgrade a resp in the load buffer *) *)
(* | SeqStep.                (* drive the sequential instruction machine *) *)


(* Definition leakage_of_AM {R} (m: ActionMethod R) : LeakAction := *)
(*   match m with *)
(*   | EnqResp IMEM resp => LeakIMemEnqResp resp.(mem_resp_addr) resp.(mem_resp_data) *)
(*   | EnqResp DMEM resp => LeakDMemEnqResp resp.(mem_resp_addr)  *)
(*   | DeqReq mem => LeakDeqReq mem *)
(*   | Tick => LeakTick *)
(*   end. *)

(* (* #[projections(primitive=no)] *) *)
(* (* Record leakage_t := *) *)
(* (* { action_leakage : list LeakAction *) *)
(* (* ; instr_leakage: list instr_leak_t *) *)
(* (* }. *) *)
(* (* Instance eta_leakage_t : Settable _ :=  *) *)
(* (*   settable! Build_leakage_t<action_leakage; instr_leakage>. *) *)

(* Class SpecParams := { *)
(*   specDriver : list (leakage_t -> list StepT); *)
(*   fifo1Spec: forall T, Inhabited T -> Fifo1Spec.SpecParams (Val := T) *)
(* }. *)

(* Section WithContext. *)
(*   Context {isaParams: IsaParams}. *)
(*   Context {specParams: SpecParams}. *)
(*   Notation rfSpec := (rfSpec (Val := mword) (initVal := zeroes) (log_nregs := log_nregs)).   *)
(*   Notation loadBufferSpec := (LoadBufferSpec.spec (Val := mword) (width := width)). *)
(*   Notation addr_t := mword. *)
(*   Instance fifo1Params `{Inhabited T}: Fifo1Spec.SpecParams (Val := T) := *)
(*     fifo1Spec T _. *)

(*   Record e2w_bookkeeping := *)
(*   { e2w_output_alu : mword; *)
(*     e2w_nextPc : mword; *)
(*     e2w_inst : mword  *)
(*   }. *)

(*   Inductive stage_t := *)
(*   | FetchAndComputeLeakage *)
(*   | IssueMem (e2w_book: e2w_bookkeeping) *)
(*   | Writeback (e2w_book: e2w_bookkeeping). *)

(*   #[projections(primitive=no)] *)
(*   Record ghost_st_t := *)
(*   { GhostLogSteps: list (list StepT) *)
(*   ; GhostDebug : list string *)
(*   ; GhostCommitted : list mword                       *)
(*   }. *)
(*   Instance eta_ghost_st_t : Settable _ := *)
(*     settable! Build_ghost_st_t<GhostLogSteps; GhostDebug; GhostCommitted>. *)

(*   #[projections(primitive=no)] *)
(*   Record base_st_t := *)
(*   { Pc: addr_t  *)
(*   ; Stage : stage_t *)
(*   ; Rf : State rfSpec *)
(*   (* Internal load buffers *) *)
(*   ; MemIBuffer: State loadBufferSpec *)
(*   (* Internal dmem buffer *) *)
(*   ; ToDMemBuffer: State (Fifo1Spec.spec (Val := mem_req_t)) *)
(*   (* External facing queues *) *)
(*   ; ToIMem : State (Fifo1Spec.spec (Val := mem_req_t)) *)
(*   ; ToDMem : State (Fifo1Spec.spec (Val := mem_req_t)) *)
(*   ; FromIMem : State (Fifo1Spec.spec (Val := mem_resp_t)) *)
(*   ; FromDMem : State (Fifo1Spec.spec (Val := mem_resp_t)) *)
(*   ; Leakage: leakage_t *)
(*   }. *)
(*   Instance eta_base_st_t : Settable _ :=  *)
(*     settable! Build_base_st_t<Pc; Stage; Rf; MemIBuffer; ToDMemBuffer; *)
(*                               ToIMem; ToDMem; FromIMem; FromDMem; Leakage>. *)

(*   #[projections(primitive=no)] *)
(*   Record st_t := *)
(*   { BaseSt: base_st_t *)
(*   (* Ghost state *) *)
(*   ; GhostSt : ghost_st_t *)
(*   }. *)
(*   Instance eta_st_t : Settable _ :=  *)
(*     settable! Build_st_t<BaseSt;GhostSt>. *)

(*   Definition initial_base_st (pc: addr_t) : base_st_t := *)
(*     {| Pc := pc *)
(*      ; Stage := FetchAndComputeLeakage *)
(*      ; Rf := initialState rfSpec *)
(*      ; MemIBuffer:= initialState loadBufferSpec *)
(*      ; ToDMemBuffer := initialState Fifo1Spec.spec *)
(*      ; ToIMem := initialState Fifo1Spec.spec *)
(*      ; ToDMem := initialState Fifo1Spec.spec  *)
(*      ; FromIMem := initialState Fifo1Spec.spec *)
(*      ; FromDMem := initialState Fifo1Spec.spec *)
(*      ; Leakage := {| action_leakage := []; *)
(*                      instr_leakage := [] *)
(*                   |} *)
(*     |}. *)

(*   Definition initial_ghost_st : ghost_st_t := *)
(*     {| GhostLogSteps := []  *)
(*      ; GhostDebug := [] *)
(*      ; GhostCommitted := [] *)
(*     |}. *)

(*   Definition initial_st (pc: addr_t): st_t := *)
(*     {| BaseSt := initial_base_st pc *)
(*      ; GhostSt := initial_ghost_st *)
(*     |}. *)
(*   Coercion BaseSt : st_t >-> base_st_t. *)
(*   Coercion GhostSt : st_t >-> ghost_st_t. *)

(*   Inductive BaseVMethod : Type -> Type :=  *)
(*   | pc : forall {R}, Reg.ValueMethod mword R -> BaseVMethod R *)
(*   | stage : forall {R}, Reg.ValueMethod stage_t R -> BaseVMethod R *)
(*   | rf : forall {R}, Rf.ValueMethod (Val := mword) (log_nregs := Params.log_nregs) R -> BaseVMethod R *)
(*   | memIBuffer : forall {R}, LoadBufferAPI.ValueMethod (Val := mword) (width := width) R -> BaseVMethod R *)
(*   | toDMemBuffer: forall {R}, Fifo1API.ValueMethod mem_req_t R -> BaseVMethod R *)
(*   | toIMem : forall {R}, Fifo1API.ValueMethod mem_req_t R -> BaseVMethod R *)
(*   | toDMem : forall {R}, Fifo1API.ValueMethod mem_req_t R -> BaseVMethod R *)
(*   | fromIMem : forall {R}, Fifo1API.ValueMethod mem_resp_t R -> BaseVMethod R *)
(*   | fromDMem : forall {R}, Fifo1API.ValueMethod mem_resp_t R -> BaseVMethod R *)
(*   | getLeakage : BaseVMethod leakage_t. *)

(*   Inductive BaseMethod : Type -> Type :=  *)
(*   | callPc : forall {R}, Reg.ActionMethod mword R -> BaseMethod R *)
(*   | callStage : forall {R}, Reg.ActionMethod stage_t R -> BaseMethod R *)
(*   | callRf : forall {R}, Rf.ActionMethod (Val := mword) (log_nregs := Params.log_nregs) R -> BaseMethod R *)
(*   | callMemIBuffer : forall {R}, LoadBufferAPI.ActionMethod (Val := mword) (width := width) R -> BaseMethod R *)
(*   | callToDMemBuffer: forall {R}, Fifo1API.ActionMethod mem_req_t R -> BaseMethod R *)
(*   | callToIMem : forall {R}, Fifo1API.ActionMethod mem_req_t R -> BaseMethod R *)
(*   | callToDMem : forall {R}, Fifo1API.ActionMethod mem_req_t R -> BaseMethod R *)
(*   | callFromIMem : forall {R}, Fifo1API.ActionMethod mem_resp_t R -> BaseMethod R *)
(*   | callFromDMem : forall {R}, Fifo1API.ActionMethod mem_resp_t R -> BaseMethod R *)
(*   | addInstrLeakage : instr_leak_t -> BaseMethod unit *)
(*   | addActionLeakage : forall {R}, ActionMethod R -> BaseMethod unit *)
(*   | addSeqSteps : list StepT -> BaseMethod unit *)
(*   | addDebug : string -> BaseMethod unit *)
(*   | addCommitted : mword -> BaseMethod unit. *)

(*   Notation "'BaseRegAction(' m ',' proj ',' st ')' " := *)
(*         (let '(v, mst') := Reg.EvalActionMethod m (proj%function (BaseSt st)) in *)
(*          (v, st <| BaseSt := (BaseSt st) <| proj := mst' |> |>)) (at level 100). *)
(*   Notation "'BaseRegValue(' m ',' proj ',' st ')' " := *)
(*         (Reg.EvalValueMethod m (proj%function (BaseSt st))) (at level 100, only parsing).  *)
(*   Notation "'BaseAction(' specFn ',' m ',' proj ',' st ')' " := *)
(*       (let '(v, mst') := EvalMethod specFn m (proj%function (BaseSt st)) in *)
(*        (v, st <| BaseSt := (BaseSt st) <| proj := mst' |> |>)) (at level 100, only parsing). *)
(*   Notation "'BaseValue(' spec ',' m ',' proj ',' st ')' " := *)
(*       (EvalVMethod spec m (proj%function (BaseSt st))) (at level 100, only parsing). *)


(*   Definition evalBaseMethod {A} (m: BaseMethod A) (st: st_t) : A * st_t := *)
(*     let base := st.(BaseSt) in  *)
(*     let ghost := st.(GhostSt) in  *)
(*     match m with *)
(*     | callPc m => BaseRegAction(m, Pc, st) *)
(*     | callStage m => BaseRegAction(m, Stage, st) *)
(*     | callRf m => BaseAction(rfSpec, m, Rf, st) *)
(*     | callMemIBuffer m => BaseAction(LoadBufferSpec.spec, m, MemIBuffer, st) *)
(*     | callToDMemBuffer m => BaseAction(Fifo1Spec.spec, m, ToDMemBuffer, st) *)
(*     | callToIMem m => BaseAction(Fifo1Spec.spec, m, ToIMem, st) *)
(*     | callToDMem m => BaseAction(Fifo1Spec.spec, m, ToDMem, st) *)
(*     | callFromIMem m => BaseAction(Fifo1Spec.spec, m, FromIMem, st) *)
(*     | callFromDMem m => BaseAction(Fifo1Spec.spec, m, FromDMem, st) *)
(*     | addInstrLeakage instr => *)
(*         ((), st <| BaseSt := base <| Leakage ::= fun leak => leak <| instr_leakage := leak.(instr_leakage) ++ [instr] |> |> |>) *)
(*     | addActionLeakage am => *)
(*         ((), st <| BaseSt := base <| Leakage ::= fun leak => leak <| action_leakage := leak.(action_leakage) ++ [leakage_of_AM am] |> |> |>) *)
(*     | addSeqSteps steps => *)
(*         ((), st <| GhostSt := ghost <| GhostLogSteps ::= fun prev => prev ++ [steps] |> |>) *)
(*     | addDebug s => *)
(*         ((), st <| GhostSt := ghost <| GhostDebug ::= cons s |> |>) *)
(*     | addCommitted s => *)
(*         ((), st <| GhostSt := ghost <| GhostCommitted ::= cons s |> |>) *)
(*     end. *)

(*   Definition evalBaseVMethod {A} (m: BaseVMethod A) (st: st_t) : A := *)
(*     let base := st.(BaseSt) in  *)
(*     let ghost := st.(GhostSt) in  *)
(*     match m with *)
(*     | pc m => BaseRegValue(m, Pc, st) *)
(*     | stage m => BaseRegValue(m, Stage, st) *)
(*     | rf m => BaseValue(rfSpec, m, Rf, st) *)
(*     | memIBuffer m => BaseValue(LoadBufferSpec.spec, m, MemIBuffer, st) *)
(*     | toDMemBuffer m => BaseValue(Fifo1Spec.spec, m, ToDMemBuffer, st) *)
(*     | toIMem m => BaseValue(Fifo1Spec.spec, m, ToIMem, st) *)
(*     | toDMem m => BaseValue(Fifo1Spec.spec, m, ToDMem, st) *)
(*     | fromIMem m => BaseValue(Fifo1Spec.spec, m, FromIMem, st) *)
(*     | fromDMem m => BaseValue(Fifo1Spec.spec, m, FromDMem, st) *)
(*     | getLeakage => st.(Leakage) *)
(*     end. *)

(*   Definition base (init_pc: mword) : Spec _ _ :=  *)
(*     {| State := st_t; *)
(*        EvalVMethod A := evalBaseVMethod; *)
(*        EvalMethod A := evalBaseMethod; *)
(*        initialState := initial_st init_pc|}. *)

(*   Notation fifo1_first := Fifo1API.First. *)
(*   Notation fifo1_empty := Fifo1API.Empty. *)
(*   Notation fifo1_full := Fifo1API.Full. *)
(*   Notation fifo1_deq := Fifo1API.Deq. *)
(*   Notation fifo1_enq := Fifo1API.Enq. *)

(*   Definition toMem (mem: mem_type) {T} := *)
(*      match mem with *)
(*      | IMEM => @toIMem T *)
(*      | DMEM => @toDMem T *)
(*      end. *)
(*   Definition fromMem (mem: mem_type) {T} := *)
(*      match mem with *)
(*      | IMEM => @fromIMem T *)
(*      | DMEM => @fromDMem T *)
(*      end. *)

(*   Definition callToMem (mem: mem_type) {T} := *)
(*      match mem with *)
(*      | IMEM => @callToIMem T *)
(*      | DMEM => @callToDMem T *)
(*      end. *)
(*   Definition callFromMem (mem: mem_type) {T} := *)
(*      match mem with *)
(*      | IMEM => @callFromIMem T *)
(*      | DMEM => @callFromDMem T *)
(*      end. *)

(*   (* We want to say value methods (observations) depend only on the *)
(*      leakage trace.  *)
(*      - can_deq_req/can_enq_resp (=timing of memory loads/stores) *)
(*        should be a function of leakage trace *)
(*      - addresses of loads/stores should be a function of leakage trace *)

(*      We should be able to state a corollary saying that addresses of *)
(*      loads/store are a function of leakage trace... assuming something *)
(*      from memory? *)
(*    *) *)

(*   Notation prog := (prog BaseVMethod BaseMethod). *)
(*   Notation expr := (expr BaseVMethod). *)
(*   Definition peek_req (mem : mem_type): expr mem_req_t := *)
(*     {|{ v ← (toMem mem) fifo1_first; *)
(*         return v *)
(*     }|}. *)

(*   Definition can_deq_req (mem: mem_type): expr bool := *)
(*     {|{ empty ← (toMem mem) fifo1_empty; *)
(*         return (negb empty) *)
(*     }|}. *)

(*   Definition can_enq_resp (mem: mem_type): expr bool := *)
(*     {|{ full ← (fromMem mem) fifo1_full; *)
(*         return (negb full) *)
(*     }|}. *)

(*   Definition enq_resp (mem: mem_type) (arg: mem_resp_t) : prog unit := *)
(*     {{ (callFromMem mem) (fifo1_enq arg);; *)
(*        pass *)
(*     }}. *)

(*   Definition deq_req (mem: mem_type): prog unit := *)
(*     {{ (callToMem mem) fifo1_deq;; *)
(*        pass *)
(*     }}. *)

(*   (* Single outstanding memory request *) *)
(*   Definition fetch_and_compute_leakage : prog (option instr_leak_t) := *)
(*     {{ _pc ← pc Reg.Read; *)
(*        ibuffer_val ← memIBuffer (LoadBufferAPI.Lookup _pc); *)
(*        match ibuffer_val with *)
(*        | Some instr => *)
(*           let dinst := decode instr in *)
(*           let rs1_idx := dinst.(dInst_rs1) in  *)
(*           let rs2_idx := dinst.(dInst_rs2) in  *)
(*           let rd_idx := dinst.(dInst_rd) in *)
(*           let rd_valid := dinst.(dInst_rdValid) in  *)
(*           rs1 ← rf (Rf.Read rs1_idx); *)
(*           rs2 ← rf (Rf.Read rs2_idx); *)
(*           let output_alu := execALU dinst rs1 rs2 in  *)
(*           let '(taken, nextPC) := execControl dinst _pc rs1 rs2 in *)
(*           if isMemory dinst.(dInst_type) then *)
(*              toDMemBuffer_full ← toDMemBuffer fifo1_full; *)
(*              if (toDMemBuffer_full: bool) then *)
(*                 return None (* Should not reach; unless dmem is poorly behaved *) *)
(*              else  *)
(*                let addr := memAddr dinst rs1 in  *)
(*                let req := *)
(*                  if isStore dinst.(dInst_type) then *)
(*                    {| mem_req_is_store := true; *)
(*                       mem_req_addr := addr; *)
(*                       mem_req_data := rs2 *)
(*                    |} *)
(*                  else  *)
(*                    {| mem_req_is_store := false; *)
(*                       mem_req_addr := addr; *)
(*                       mem_req_data := zeroes *)
(*                    |} in *)
(*                callToDMemBuffer (fifo1_enq req);;  *)
(*                (* memIBuffer (LoadBufferAPI.Downgrade _pc);; *) *)
(*                callStage (Reg.Write (IssueMem {| e2w_output_alu := output_alu; (* Don't care *) *)
(*                                                 e2w_nextPc := nextPC; *)
(*                                                 e2w_inst := instr  *)
(*                                            |}));; *)
(*                return (Some {| leak_taken := taken; *)
(*                                leak_nextPC:= nextPC; *)
(*                                leak_mul_zero := None; *)
(*                                leak_dmem_addr := Some addr *)
(*                              |}) *)
(*           else if isMul dinst.(dInst_type) then *)
(*             let output_mul := bv_mul rs1 rs2 in *)
(*             (* memIBuffer (LoadBufferAPI.Downgrade _pc);; *) *)
(*             callStage (Reg.Write (IssueMem {| e2w_output_alu := output_mul; *)
(*                                               e2w_nextPc := nextPC; *)
(*                                               e2w_inst := instr  *)
(*                                        |}));; *)
(*             return (Some {| leak_taken := taken; *)
(*                             leak_nextPC:= nextPC; *)
(*                             leak_mul_zero := Some (bool_decide (rs1 = zeroes \/ rs2 = zeroes)); *)
(*                             leak_dmem_addr := None; *)
(*                          |}) *)
(*           else (* ALU *) *)
(*             (* memIBuffer (LoadBufferAPI.Downgrade _pc);; *) *)
(*             callStage (Reg.Write (IssueMem {| e2w_output_alu := output_alu; *)
(*                                            e2w_nextPc := nextPC; *)
(*                                            e2w_inst := instr  *)
(*                                         |}));; *)
(*             return (Some {| leak_taken := taken; *)
(*                             leak_nextPC:= nextPC; *)
(*                             leak_mul_zero := None; *)
(*                             leak_dmem_addr := None *)
(*                           |}) *)
(*        | None => Return None *)
(*        end *)
(*     }}. *)

(*   Definition issue_mem (e2w_book: e2w_bookkeeping) : prog unit := *)
(*     {{ let dinst := decode e2w_book.(e2w_inst) in *)
(*        if isMemory dinst.(dInst_type) then *)
(*          toDMem_full ← toDMem fifo1_full; *)
(*          toDMemBuffer_empty ← toDMemBuffer fifo1_empty; *)
(*          toDMemBuffer_value ← toDMemBuffer fifo1_first; *)
(*          if (toDMem_full: bool) then *)
(*            pass (* should not happen *) *)
(*          else if (toDMemBuffer_empty : bool) then *)
(*            pass (* should not happen *) *)
(*          else  *)
(*            callToDMem (fifo1_enq toDMemBuffer_value);; *)
(*            callToDMemBuffer fifo1_deq;; *)
(*            callStage (Reg.Write (Writeback e2w_book));; *)
(*            pass *)
(*        else  *)
(*          callStage (Reg.Write (Writeback e2w_book));; *)
(*          pass *)
(*      }}. *)

(*   Definition writeback (e2w_book: e2w_bookkeeping): prog unit := *)
(*     {{ let dinst := decode e2w_book.(e2w_inst) in *)
(*        let isLoad := isLoad dinst.(dInst_type)in  *)
(*        fromDMem_empty ← fromDMem fifo1_empty; *)
(*        if (isLoad && fromDMem_empty) then *)
(*          (* Response not ready *) *)
(*          pass *)
(*        else  *)
(*          let/prog data :=  *)
(*            (if isLoad then *)
(*                resp ← fromDMem fifo1_first; *)
(*                callFromDMem fifo1_deq;; *)
(*                return resp.(mem_resp_data) *)
(*             else Return e2w_book.(e2w_output_alu)) in  *)
(*          (* Update PC *) *)
(*          callPc (Reg.Write e2w_book.(e2w_nextPc));; *)
(*          callStage (Reg.Write FetchAndComputeLeakage);; *)
(*          addCommitted e2w_book.(e2w_inst);; *)
(*          (* Update data *) *)
(*          if dinst.(dInst_rdValid) then *)
(*            callRf (Rf.Write dinst.(dInst_rd) data);; *)
(*            pass *)
(*          else pass *)
(*      }}. *)

(*   Definition loadInstr (addr: mword) : prog unit := *)
(*     {{ _toIMem_full ← toIMem fifo1_full; *)
(*        if (_toIMem_full: bool) then *)
(*          pass *)
(*        else  *)
(*          let mem_req := {| mem_req_is_store := false; *)
(*                            mem_req_addr := addr; *)
(*                            mem_req_data := zeroes |} in  *)
(*          callToIMem (fifo1_enq mem_req);; *)
(*          callMemIBuffer (LoadReq addr);; *)
(*          pass *)
(*      }}. *)

(*   Definition recvImemResp (keep: bool): prog unit := *)
(*     {{ fromIMem_empty ← fromIMem fifo1_empty; *)
(*        if (fromIMem_empty: bool) then *)
(*          pass *)
(*        else  *)
(*          resp ← fromIMem fifo1_first; *)
(*          callFromIMem fifo1_deq;; *)
(*          if keep then *)
(*            callMemIBuffer (LoadResp resp.(mem_resp_addr) resp.(mem_resp_data));; *)
(*            pass *)
(*          else *)
(*            callMemIBuffer (ForgetResp resp.(mem_resp_addr));; *)
(*            pass *)
(*      }}. *)

(*   Definition downgradeIMem (addr: mword): prog unit := *)
(*     {{ callMemIBuffer (LoadBufferAPI.Downgrade addr);; *)
(*        pass *)
(*     }}. *)

(*   Definition seqStep : prog unit := *)
(*     {{ _stage ← stage Reg.Read; *)
(*        match _stage with *)
(*        | FetchAndComputeLeakage =>  *)
(*            let/prog leakage := fetch_and_compute_leakage in  *)
(*            (match leakage with  *)
(*             | Some leakage => addInstrLeakage leakage;; pass *)
(*             | None => pass *)
(*             end) *)
(*        | IssueMem e2w => *)
(*            callProg (issue_mem e2w); *)
(*            pass *)
(*        | Writeback e2w => *)
(*            callProg (writeback e2w); *)
(*            pass *)
(*        end *)
(*     }}. *)

(*   Definition step (s: StepT) : prog unit := *)
(*     match s with  *)
(*     | LoadInstr addr => loadInstr addr *)
(*     | RecvIMemResp keep => recvImemResp keep *)
(*     | DowngradeIMem addr => downgradeIMem addr *)
(*     | SeqStep => seqStep *)
(*     end. *)

(*   (* At each cycle, we can do some sequence of steps, determined as a *)
(*      function of the leakage trace. *)
(*    *) *)
(*   Definition tick : prog unit := *)
(*     {{ seqPrograms (map (fun f =>  *)
(*                           leakage ← getLeakage; *)
(*                           let steps := f leakage in *)
(*                           addSeqSteps steps;; *)
(*                           seqPrograms (map step steps) (Return tt) *)
(*                        ) specDriver) (Return tt) }}. *)

(*   Definition impl_VM [R] (m: ValueMethod R) : expr R := *)
(*     match m with *)
(*     | CanEnqResp mem => can_enq_resp mem *)
(*     | CanDeqReq mem => can_deq_req mem *)
(*     | Peek mem => peek_req mem *)
(*     end. *)

(*   Definition impl_AM [R] (m: ActionMethod R) : prog R := *)
(*     {{ let/prog ret := ((match m with *)
(*                          | EnqResp mem arg => enq_resp mem arg *)
(*                          | DeqReq mem => deq_req mem *)
(*                          | Tick => tick *)
(*                          end):prog R) in  *)
(*       addActionLeakage m;; (* Needs to come after method call, so that tick happens correctly *) *)
(*       return ret }}. *)

(*   Definition isa_machine (init_pc: mword) := object (base init_pc) impl_VM impl_AM. *)
(*   Definition isa_machine_spec (init_pc: mword) := coarsen (isa_machine init_pc). *)
  
(* End WithContext. *)

