(* From stdpp Require Import base finite nmap. *)
(* From granite.core Require Import *)
(*   Bits *)
(*   Object *)
(*   Program *)
(*   ProgramOps. *)
(* From RecordUpdate Require Import RecordSet. *)

(* From granite.app Require Import  *)
(*   PipelinedCommon *)
(*   PipelinedAPI *)
(*   TopImpl *)
(*   ToyIsaMachine. *)

(* Set Primitive Projections. *)
(* Import RecordSetNotations. *)


(* Section WithContext. *)
(*   Context {isaParams: IsaParams}. *)
(*   Context {specParams: SpecParams}. *)
(*   Context {mmioParams: MMIO.SpecParams}. *)
(*   Context (init_pc: mword). *)

(*   Context (imemParams: MemorySpec.SpecParams). *)
(*   Context (dmemParams: MemorySpec.SpecParams). *)
(*   Context (init_imem init_dmem: MemorySpec.memory_t). *)

(*   #[projections(primitive=no)] *)
(*   Record st_t :=  *)
(*   { Cpu: ToyIsaMachine.st_t *)
(*   ; Imem: MemorySpec.st_t *)
(*   ; Dmem: MemorySpec.st_t *)
(*   ; Mmio: MMIO.st_t *)
(*   }. *)
(*   Instance eta_st_t : Settable _ := settable! Build_st_t<Cpu; Imem; Dmem; Mmio>. *)

(*   Definition initial_st : st_t := *)
(*     {| Cpu := ToyIsaMachine.initial_st init_pc; *)
(*        Imem := MemorySpec.initial_st init_imem; *)
(*        Dmem := MemorySpec.initial_st init_dmem; *)
(*        Mmio := MMIO.initial_st  *)
(*     |}. *)

(*   Definition evalBaseMethod {A} (m: TopImpl.BaseMethod A) (st: st_t) : A * st_t := *)
(*     match m with *)
(*     | TopImpl.cpu_ m => Action(ToyIsaMachine.isa_machine_spec init_pc, m, Cpu, st) *)
(*     | TopImpl.imem_ m => *)
(*         Action(MemorySpec.spec (specParams := imemParams) init_imem, m, Imem, st) *)
(*     | TopImpl.dmem_ m => *)
(*         Action(MemorySpec.spec (specParams := dmemParams) init_dmem, m, Dmem, st) *)
(*     | TopImpl.mmio_ m => *)
(*         Action(MMIO.spec (specParams := mmioParams), m, Mmio, st) *)
(*     end. *)

(*   Definition evalBaseVMethod {A} (m: TopImpl.BaseVMethod A) (st: st_t) : A := *)
(*     match m with *)
(*     | TopImpl.cpu m => Value(ToyIsaMachine.isa_machine_spec init_pc, m, Cpu, st) *)
(*     | TopImpl.imem m => *)
(*         Value(MemorySpec.spec (specParams := imemParams) init_imem, m, Imem, st) *)
(*     | TopImpl.dmem m => *)
(*         Value(MemorySpec.spec (specParams := dmemParams) init_dmem, m, Dmem, st) *)
(*     | TopImpl.mmio m => *)
(*         Value(MMIO.spec (specParams := mmioParams), m, Mmio, st) *)
(*     end. *)

(*   Definition base : Spec _ _ :=  *)
(*     {| State := st_t; *)
(*        EvalVMethod A := evalBaseVMethod; *)
(*        EvalMethod A := evalBaseMethod; *)
(*        initialState := initial_st *)
(*     |}. *)

(*   Definition top := object base (TopImpl.impl_VM ) (TopImpl.impl_AM isMMIO). *)
(*   Definition top_spec := coarsen top. *)

(*   Definition step_n (n: nat) : Program.prog TopAPI.VMethod TopAPI.Method unit := *)
(*     seqPrograms (map (fun _ => CallMet TopAPI.Tick (fun _ => pass)) (seq 0 n)) pass. *)

(* End WithContext. *)
