#!/usr/bin/env python3
"""Convert a flat little-endian RV32 binary into a Coq program definition.

Emits a Coq source file containing just the `list mword` literal for the
binary, in the style of `prog__double_bin` in
granite2/isaSpec/TopLevelSpec.v.
"""

import argparse
import os
import struct
import sys


PREAMBLE = """\
From stdpp Require Import base finite nmap stringmap vector.
From Stdlib Require Import Strings.String.

From granite.isaSpec Require Import Common.

From quartz.lang Require Syntax.
Import (coercions) Syntax.BV.
Import Syntax.BV.
"""


def read_words(path: str) -> list[int]:
    with open(path, "rb") as f:
        data = f.read()
    if len(data) % 4 != 0:
        sys.exit(f"error: {path} length {len(data)} is not a multiple of 4")
    return list(struct.unpack(f"<{len(data) // 4}I", data))


def emit(words: list[int], name: str, src_path: str) -> str:
    bin_id = f"prog__{name}_bin"
    out = []
    out.append(
        f"(* Auto-generated by bin_to_coq.py from {os.path.basename(src_path)}.\n"
        f"   Do not edit by hand; regenerate with `make coq`. *)\n\n"
    )
    out.append(PREAMBLE)
    out.append("\n")
    out.append(f"Definition {bin_id} : list mword :=\n")
    for i, w in enumerate(words):
        sep = "[ " if i == 0 else "; "
        out.append(f"  {sep}0x{w:08x}\n")
    out.append("  ].\n")
    return "".join(out)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("input", help="flat RV32 binary (e.g. salsa20.flat.bin)")
    ap.add_argument("-o", "--output", required=True, help="output .v file")
    ap.add_argument(
        "--name",
        default=None,
        help="program name stem (default: derived from input filename)",
    )
    args = ap.parse_args()

    words = read_words(args.input)
    name = args.name or os.path.basename(args.input).split(".")[0]

    text = emit(words, name, args.input)
    with open(args.output, "w") as f:
        f.write(text)
    print(f"wrote {args.output}: {len(words)} instructions, name={name}")


if __name__ == "__main__":
    main()
